# Generated by Django 4.0.1 on 2022-01-16 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Burgalter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som_sana', models.DateTimeField()),
                ('tolagan_puli', models.IntegerField(blank=True)),
                ('qarz_minus', models.IntegerField(blank=True)),
                ('tavar_miqdori', models.IntegerField()),
                ('tavarga_tolagan_puli', models.IntegerField()),
                ('nasiyasi', models.IntegerField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.client')),
                ('ombor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.ombor')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.product')),
            ],
        ),
    ]
